### ISSUE TITLE
editing primitive geometry properties does not work

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#695] opened 2024-07-09 15:23 UTC
this must have worked before so assuming this is an undo / redo regression?

to reproduce:
- create a new scene
- add new pro layer, primitive geometry
- select and open property panel
- change radius of circle --> this does NOT work as expected
- Instead of allowing the user to update the radius property, the value is set to 1 (to verify, go to viewer mode, come back to inspector, re-select object and inspect properties)

reproduction example2:
- https://3dstreet.app/#https://streetmix.net/kfarr/3/example-street
- select one of the ocean blocks
- change the material metal property, it is set to 0 no matter what value is selected in the editor
- go to viewer mode and return to editor to see the metalness value 0

![image](https://github.com/3DStreet/3dstreet/assets/470477/fa3bcc73-6af0-4974-a0e3-0939441142c7)

**Comment by vincentfretin** [comment] 2024-07-15 11:32
Yes, that's a regression since undo was merged.
In
https://github.com/3DStreet/3dstreet/blob/fb8ddf0d860ef45dfda9f4aee58fa5795f9a8999/src/editor/lib/commands/EntityUpdateCommand.js#L48-L50
component.schema[payload.property] is undefined, so for example materialComponent.schema['metalness'] is undefined. I guess it's an issue with all the dynamic schema like material and geometry.

**Comment by vincentfretin** [comment] 2024-07-15 11:47
I fixed the issue in #708

**Closed** 2024-07-15 16:11 UTC
