### ISSUE TITLE
'DOMSubtreeModified' mutation event is deprecated (in assets.js)

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet#682] opened 2024-06-28 17:08 UTC
There is a warning message in Dev Tools:
`[Deprecation] Listener added for a 'DOMSubtreeModified' mutation event. This event type is deprecated, and will be removed from this browser VERY soon. Usage of this event listener will cause performance issues today, and represents a large risk of imminent site breakage. Consider using MutationObserver instead. See https://chromestatus.com/feature/5083947249172480 for more information.`
`DOMSubtreeModified` is using here:
https://github.com/3DStreet/3dstreet/blob/afec8fd93a8bf54549ce809a1d06fd131a8ff1fd/src/assets.js#L345

**Comment by vincentfretin** [comment] 2024-07-29 08:20
Duplicate of #733

**Closed by vincentfretin** 2024-07-29 08:20 UTC
